# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48fffdd449eebb78685c062ff7f117e5b43b3d637a7b6ef724c70f576b99dae403393cec1d43332ddd1671f353c7526a1f7035ed5cc955657f663e46ee3c1c7b

test:
  secret_key_base: 8ca4c3094cbdca71eeb6de8c8a782b77d089d74aaa379c7ddf875a61120370e7fa4443f5322c20082ef26a963966bdaedeedaa493bd6d32780c1e08318968bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
